### ISSUE TITLE
Add Action button directly in UI

### ISSUE THREAD

**Issue by enoch85** [enoch85/ovms-mqtt-integration#40]
Is that even possible?

It should use the `send` command to `server v3 update all`.

Using default actions are supported, and working from UI already, but not directly inside the integration.

**Comment by enoch85** [comment]
Well, maybe it's better to do as a button with a helper.

```
show_name: true
show_icon: true
type: button
tap_action:
  action: perform-action
  perform_action: ovms.send_command
  target: {}
  data:
    timeout: 10
    vehicle_id: REG123
    command: server v3 update all
entity: input_button.ovms_update_all
hold_action:
  action: none
name: "REG123: update all"
```
